name: Flutter Windows Build

on:
  workflow_dispatch:  # מאפשר לך להריץ ידנית את הבנייה
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9' # שנה לגרסה שאתה צריך

      - name: Enable Windows support
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows --debug

      - name: Upload Build Folder
        uses: actions/upload-artifact@v4
        with:
          name: flutter-windows-build
          path: build/windows/
